name: squared_circle_universe
description: A wrestling promoter management simulation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6
  audioplayers: ^6.5.1 # <--- NEW: For Sound Effects
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # ASSETS REGISTRATION
  assets:
    - assets/images/
    - assets/audio/ # <--- NEW: Registers the sound folder